---
title: "Lead Inequality"
author: "Richard Montes Lemus"
format: html
---
```{r}
# load packages
library(tidyverse)
library(janitor)
library(dplyr)
```

```{r}
# read in and clean data 
rm(list = ls())
stl_lead_prop <- read_csv(here::here("data", "stl_blood_lead.csv")) %>% 
  clean_names() 
```
```{r}
# add column for % of white 
stl_lead_prop <- stl_lead_prop %>% 
  mutate(prop_white = (white/total_pop)*100)
```

```{r}
# create scatter plot 

stl_lead_plot <- stl_lead_prop %>% 
  ggplot(aes(x = pct_elevated, 
             y = prop_white)) + 
  geom_point(color = "red", alpha = 0.5, size = 2) + 
  labs(x = "Elevated blood lead levels (micrograms per deciliter)", 
       y = "White population (%)", 
       title = "White population % per elevated blood lead level")

  
```

Higher levels of elevated blood levels are associated with tracts that contain a lower white population %. 

```{r fig.width=8, fig.height=6}
stl_lead_plot
```

```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```


```{r}
stl_elev_plot <- stl_lead_prop %>% 
  ggplot(aes(x = pct_elevated)) +
  geom_histogram(color = "darkblue", 
                 fill = "darkblue",
                 binwidth = 2) + 
  labs(x = "Elevated blood lead levels (micrograms per deciliter)")
stl_elev_plot
```

```{r}
ggsave(here::here("figs", "stl_elev_plot.jpg"), height = 6, width = 5)

```

